# Generated by Django 4.0.6 on 2022-09-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distancelearningapp', '0003_reviews_user_alter_profile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
